#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""======HEAD======"""

import os
import sys

path = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.abspath(path + "/../py_utility"))
from gr_module import *

"""======AFTER-HEAD======"""

import random
import string
import subprocess

"""======---======"""

def buildblock(size):
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(size))

com_cnt = int(sys.argv[1])
file_cnt = int(sys.argv[2])
char_cnt = int(sys.argv[3])

if not os.path.exists("fake"):
    os.makedirs("fake")

for i in range(com_cnt):
    for j in range(file_cnt):
        name = buildblock(10) + ".txt"
        f = open("fake/" + name, "w")
        f.write(buildblock(char_cnt))
        f.close()
    popen_read("git add -A")
    popen_read("git commit -m \"<fake>\"")
